# Generated by Django 3.2.4 on 2023-08-03 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties_rooms', '0003_alter_room_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='room', to=settings.AUTH_USER_MODEL),
        ),
    ]
