# Generated by Django 3.2.4 on 2023-07-31 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties_rooms', '0002_auto_20230731_1752'),
        ('messages_tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='properties_rooms.room'),
        ),
        migrations.AlterField(
            model_name='message',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
