# Generated by Django 3.2.4 on 2023-07-31 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties_rooms', '0001_initial'),
        ('tasks_reminders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tenant',
        ),
        migrations.AddField(
            model_name='task',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='properties_rooms.room'),
        ),
        migrations.AlterField(
            model_name='task',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='properties_rooms.property'),
        ),
    ]
